### ISSUE TITLE
[BUG] Unable to cancel preset saving.

### ISSUE THREAD

**Issue by KottV** [Chowdhury-DSP/BYOD#57]
Hi Jatin!

**Describe the bug**
If you press the "save preset" then "MyPreset" will still active until you press enter and there is no way to cancel that and/or choose another preset .

**To Reproduce**
1. Go to 'main window'
2. Click on 'Save Preset'
3. Press `Esc` or click out of preset's name text box or "next preset" button.
4. "MyPreset" is still waiting for input.

**Expected behavior**
Saving should be canceled.

**Desktop (please complete the following information):**
 - OS: Linux
 - DAW: Standalone, BespokeSynth with VST3 version
 - Version HEAD

**Comment by KottV** [comment]
yeah, interesting
I'll try to investigate how it doesn't work on Linux

**Comment by jatinchowdhury18** [comment]
Cool, thanks! With the latest commits on `main` it should also be possible to cancel the preset save action by clicking away from the presets menu.

**Comment by KottV** [comment]
It works when the text edit box is active:

Press "Save Preset"
Click on preset's name text input field.
Press `Esc` or click out of that field.
All is ok.

But it actually inactive right after selecting "Save Preset". Maybe it should changed to be active immediately?

**Comment by jatinchowdhury18** [comment]
Good to hear that Escape and clicking away are both working. For grabbing keyboard focus automatically, I think that was another platform-dependent issue. I believe it should be fixed now in the latest nightly.

Thanks!

**Comment by KottV** [comment]
Hi!
Sorry for the long answer. Sorry, I must say that it still doesn't react on Esc when Preset's field is unfocussed.

**Comment by jatinchowdhury18** [comment]
No worries! So it sounds like the presets field still doesn't have the keyboard focus when it first appears? Maybe there's something I'm missing. Would it be possible to make a screen recording of the issue happening?

**Comment by KottV** [comment]
yeah, i'll record video

**Comment by KottV** [comment]
https://user-images.githubusercontent.com/4686351/151153158-dc47e5c2-748a-4744-8597-98002992c865.mp4

here it is, after selecting "Save Preset" I clicked on canvas, hit Esc and list presets, only after putting cursor on presets name i was able to cancel

**Comment by KottV** [comment]
Well, actually I have to click to text input field to type preset's name, otherwise it's unfocused too.

**Comment by jatinchowdhury18** [comment]
Thanks for the extra info! For now I've decided to use a different workflow for saving presets, so that the user can select the preset category and stuff like that.

That said, I'll definitely keep trying to figure this issue out for other plugins that use a similar workflow.
